### ISSUE TITLE
Editing pages causes hookaborted error

### ISSUE THREAD

**Issue by elifoster** [elifoster/SatanicBot#45]
The edit caused by the $abbrv command causes the bot to die, with the error "hookaborted". Figure out what this actually means, then figure out how to fix it.

**Comment by satanicsanta** [comment]
This is caused by the Translate extension, and happens on all marked pages. I may need to use the other MediaWiki module for this, or just the api method directly.

**Comment by elifoster** [comment]
I tried MediaWiki::Bot, and it was not erroring (when I told it to not error if the code is undefined). it then said it was a success, but never actually edited the page.

**Comment by elifoster** [comment]
As of @792beb9 it no longer crashes. Now it just doesn't edit the page. I may need to use some other language for this particular command. Maybe I should generate a JSON file with the abbreviation and name, then use another language to perform the edit (JavaScript maybe?). Or maybe I could just use the web API to edit via WWW::Mechanize.

**Comment by elifoster** [comment]
All Perl modules are shit. Using Ruby for wiki stuff from now on. Will write some Ruby scripts for the existing MediaWiki commands.

**Comment by elifoster** [comment]
Mostly fixed with new Ruby code.
