### ISSUE TITLE
Wunderground/Wiki/Twitter login

### ISSUE THREAD

**Issue by elifoster** [elifoster/SatanicBot#48]
I should not log in every single time the $tweet command is run.

**Comment by Strikingwolf** [comment]
Yeah you really shouldn't :laughing:

**Comment by satanicsanta** [comment]
@strikingwolf TwitterOAuth is a bitch.

**Comment by Strikingwolf** [comment]
Yep

**Comment by elifoster** [comment]
This is also true for Wunderground and the wiki.
